version: "3"

services:
  db:
    container_name: db
    image: postgres:${POSTGRES_VERSION}
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    container_name: taller
    restart: always
    env_file: .env
    build:
      context: .
    command:
      - /bin/sh
      - -c
      - |
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/appdir
    ports:
      - '8000:8000'
    tty: true
    depends_on:
      - db

volumes:
  db-data:
