# Generated by Django 3.2.16 on 2022-11-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.PositiveIntegerField(help_text='Capacidad de aforo del edificio')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('duracion', models.PositiveIntegerField(help_text='Cantidad de horas de duración del evento.')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aforos.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Sin puntos ni guiones y con dígito verificador.', max_length=9, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField(help_text='Sin código de país y con 9')),
                ('es_menor', models.BooleanField(help_text='Indica si es un menor de edad')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aforos.evento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aforos.persona')),
            ],
        ),
    ]
